#!/usr/bin/env node
/**
 * YAMLファイルからD1用のSQLインサート文を生成するスクリプト
 *
 * 使い方:
 *   node scripts/tools/generate-d1-seed.js > db/seed.sql
 *
 * ビルド時に毎回実行してDBをフルリビルドする
 */

import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../..');
const dataDir = path.join(rootDir, 'src/data/laws');

// SQLエスケープ
function escapeSQL(str) {
  if (str === null || str === undefined) return 'NULL';
  if (typeof str !== 'string') str = JSON.stringify(str);
  return `'${str.replace(/'/g, "''")}'`;
}

// 配列をJSON文字列に変換
function arrayToJSON(arr) {
  if (!arr || !Array.isArray(arr)) return null;
  return JSON.stringify(arr);
}

// カテゴリディレクトリを取得
function getCategories() {
  return fs.readdirSync(dataDir).filter(name => {
    const fullPath = path.join(dataDir, name);
    return fs.statSync(fullPath).isDirectory();
  });
}

// 法律ディレクトリを取得
function getLaws(category) {
  const categoryDir = path.join(dataDir, category);
  return fs.readdirSync(categoryDir).filter(name => {
    const fullPath = path.join(categoryDir, name);
    return fs.statSync(fullPath).isDirectory();
  });
}

// YAMLファイルを読み込み
function loadYAML(filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    return yaml.load(content);
  } catch (e) {
    return null;
  }
}

// メイン処理
function main() {
  const sqlStatements = [];

  // 既存データを削除（FTSも含む）
  sqlStatements.push('-- Generated by generate-d1-seed.js');
  sqlStatements.push(`-- Generated at: ${new Date().toISOString()}`);
  sqlStatements.push('');
  sqlStatements.push('DELETE FROM articles_fts;');
  sqlStatements.push('DELETE FROM famous_articles;');
  sqlStatements.push('DELETE FROM chapters;');
  sqlStatements.push('DELETE FROM articles;');
  sqlStatements.push('DELETE FROM laws;');
  sqlStatements.push('');

  const categories = getCategories();

  for (const category of categories) {
    const laws = getLaws(category);

    for (const lawName of laws) {
      const lawDir = path.join(dataDir, category, lawName);

      // law_metadata.yaml を読み込み
      const metadataPath = path.join(lawDir, 'law_metadata.yaml');
      const metadata = loadYAML(metadataPath);

      if (metadata) {
        sqlStatements.push(`-- Law: ${category}/${lawName}`);
        sqlStatements.push(`INSERT INTO laws (category, name, display_name, short_name, badge, year, source, description, links) VALUES (`);
        sqlStatements.push(`  ${escapeSQL(category)},`);
        sqlStatements.push(`  ${escapeSQL(lawName)},`);
        sqlStatements.push(`  ${escapeSQL(metadata.name)},`);
        sqlStatements.push(`  ${escapeSQL(metadata.shortName || null)},`);
        sqlStatements.push(`  ${escapeSQL(metadata.badge || null)},`);
        sqlStatements.push(`  ${metadata.year || 'NULL'},`);
        sqlStatements.push(`  ${escapeSQL(metadata.source || null)},`);
        sqlStatements.push(`  ${escapeSQL(metadata.description || null)},`);
        sqlStatements.push(`  ${escapeSQL(arrayToJSON(metadata.links))}`);
        sqlStatements.push(`);`);
        sqlStatements.push('');
      }

      // chapters.yaml を読み込み
      const chaptersPath = path.join(lawDir, 'chapters.yaml');
      const chaptersData = loadYAML(chaptersPath);

      if (chaptersData && chaptersData.chapters) {
        for (const chapter of chaptersData.chapters) {
          sqlStatements.push(`INSERT INTO chapters (category, law_name, chapter, title, title_osaka, description, description_osaka, articles) VALUES (`);
          sqlStatements.push(`  ${escapeSQL(category)},`);
          sqlStatements.push(`  ${escapeSQL(lawName)},`);
          sqlStatements.push(`  ${chapter.chapter},`);
          sqlStatements.push(`  ${escapeSQL(chapter.title)},`);
          sqlStatements.push(`  ${escapeSQL(chapter.titleOsaka || null)},`);
          sqlStatements.push(`  ${escapeSQL(chapter.description || null)},`);
          sqlStatements.push(`  ${escapeSQL(chapter.descriptionOsaka || null)},`);
          sqlStatements.push(`  ${escapeSQL(arrayToJSON(chapter.articles))}`);
          sqlStatements.push(`);`);
        }
        sqlStatements.push('');
      }

      // famous_articles.yaml を読み込み
      const famousPath = path.join(lawDir, 'famous_articles.yaml');
      const famousData = loadYAML(famousPath);

      if (famousData) {
        for (const [article, badge] of Object.entries(famousData)) {
          sqlStatements.push(`INSERT INTO famous_articles (category, law_name, article, badge) VALUES (`);
          sqlStatements.push(`  ${escapeSQL(category)},`);
          sqlStatements.push(`  ${escapeSQL(lawName)},`);
          sqlStatements.push(`  ${escapeSQL(article)},`);
          sqlStatements.push(`  ${escapeSQL(badge)}`);
          sqlStatements.push(`);`);
        }
        sqlStatements.push('');
      }

      // 条文YAMLを読み込み
      const files = fs.readdirSync(lawDir).filter(f =>
        f.endsWith('.yaml') &&
        !['law_metadata.yaml', 'chapters.yaml', 'famous_articles.yaml'].includes(f)
      );

      for (const file of files) {
        const filePath = path.join(lawDir, file);
        const article = loadYAML(filePath);

        if (article && article.article !== undefined) {
          const articleNum = String(article.article);

          sqlStatements.push(`INSERT INTO articles (category, law_name, article, is_suppl, is_deleted, title, title_osaka, original_text, osaka_text, commentary, commentary_osaka) VALUES (`);
          sqlStatements.push(`  ${escapeSQL(category)},`);
          sqlStatements.push(`  ${escapeSQL(lawName)},`);
          sqlStatements.push(`  ${escapeSQL(articleNum)},`);
          sqlStatements.push(`  ${article.isSuppl ? 1 : 0},`);
          sqlStatements.push(`  ${article.isDeleted ? 1 : 0},`);
          sqlStatements.push(`  ${escapeSQL(article.title || null)},`);
          sqlStatements.push(`  ${escapeSQL(article.titleOsaka || null)},`);
          sqlStatements.push(`  ${escapeSQL(arrayToJSON(article.originalText))},`);
          sqlStatements.push(`  ${escapeSQL(arrayToJSON(article.osakaText))},`);
          sqlStatements.push(`  ${escapeSQL(arrayToJSON(article.commentary))},`);
          sqlStatements.push(`  ${escapeSQL(arrayToJSON(article.commentaryOsaka))}`);
          sqlStatements.push(`);`);
        }
      }

      sqlStatements.push('');
    }
  }

  // 出力
  console.log(sqlStatements.join('\n'));
}

main();
