#!/usr/bin/env node
/**
 * YAMLファイルからD1用のSQLインサート文を生成するスクリプト
 *
 * 使い方:
 *   node scripts/tools/generate-d1-seed.js > db/seed.sql
 *
 * ビルド時に毎回実行してDBをフルリビルドする
 */

import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../..');
const dataDir = path.join(rootDir, 'src/data/laws');

// SQLエスケープ
function escapeSQL(str) {
  if (str === null || str === undefined) return 'NULL';
  if (typeof str !== 'string') str = JSON.stringify(str);
  return `'${str.replace(/'/g, "''")}'`;
}

// 配列をJSON文字列に変換
function arrayToJSON(arr) {
  if (!arr || !Array.isArray(arr)) return null;
  return JSON.stringify(arr);
}

// カテゴリディレクトリを取得
function getCategories() {
  return fs.readdirSync(dataDir).filter((name) => {
    const fullPath = path.join(dataDir, name);
    return fs.statSync(fullPath).isDirectory();
  });
}

// 法律ディレクトリを取得
function getLaws(category) {
  const categoryDir = path.join(dataDir, category);
  return fs.readdirSync(categoryDir).filter((name) => {
    const fullPath = path.join(categoryDir, name);
    return fs.statSync(fullPath).isDirectory();
  });
}

// YAMLファイルを読み込み
function loadYAML(filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    return yaml.load(content);
  } catch (e) {
    return null;
  }
}

// メイン処理
function main() {
  const sqlStatements = [];

  // ヘッダー（スキーマは db/schema.sql で別途投入）
  sqlStatements.push(`-- Generated by generate-d1-seed.js at ${new Date().toISOString()}`);
  sqlStatements.push('-- Run db/schema.sql first, then this file');
  sqlStatements.push('');

  const categories = getCategories();

  for (const category of categories) {
    const laws = getLaws(category);

    for (const lawName of laws) {
      const lawDir = path.join(dataDir, category, lawName);

      // law_metadata.yaml を読み込み
      const metadataPath = path.join(lawDir, 'law_metadata.yaml');
      const metadata = loadYAML(metadataPath);

      if (metadata) {
        const values = [
          escapeSQL(category),
          escapeSQL(lawName),
          escapeSQL(metadata.name),
          escapeSQL(metadata.shortName || null),
          escapeSQL(metadata.badge || null),
          metadata.year || 'NULL',
          escapeSQL(metadata.source || null),
          escapeSQL(metadata.description || null),
          escapeSQL(arrayToJSON(metadata.links)),
        ].join(', ');
        sqlStatements.push(
          `INSERT INTO laws (category, name, display_name, short_name, badge, year, source, description, links) VALUES (${values});`
        );
      }

      // chapters.yaml を読み込み
      const chaptersPath = path.join(lawDir, 'chapters.yaml');
      const chaptersData = loadYAML(chaptersPath);

      if (chaptersData && chaptersData.chapters) {
        for (const chapter of chaptersData.chapters) {
          const values = [
            escapeSQL(category),
            escapeSQL(lawName),
            escapeSQL(String(chapter.chapter)),
            escapeSQL(chapter.title),
            escapeSQL(chapter.titleOsaka || null),
            escapeSQL(chapter.description || null),
            escapeSQL(chapter.descriptionOsaka || null),
            escapeSQL(arrayToJSON(chapter.articles)),
          ].join(', ');
          sqlStatements.push(
            `INSERT INTO chapters (category, law_name, chapter, title, title_osaka, description, description_osaka, articles) VALUES (${values});`
          );
        }
      }

      // famous_articles.yaml を読み込み
      const famousPath = path.join(lawDir, 'famous_articles.yaml');
      const famousData = loadYAML(famousPath);

      if (famousData) {
        for (const [article, badge] of Object.entries(famousData)) {
          const values = [
            escapeSQL(category),
            escapeSQL(lawName),
            escapeSQL(article),
            escapeSQL(badge),
          ].join(', ');
          sqlStatements.push(
            `INSERT INTO famous_articles (category, law_name, article, badge) VALUES (${values});`
          );
        }
      }

      // 条文YAMLを読み込み
      const files = fs
        .readdirSync(lawDir)
        .filter(
          (f) =>
            f.endsWith('.yaml') &&
            !['law_metadata.yaml', 'chapters.yaml', 'famous_articles.yaml'].includes(f)
        );

      for (const file of files) {
        const filePath = path.join(lawDir, file);
        const article = loadYAML(filePath);

        if (article && article.article !== undefined) {
          const articleNum = String(article.article);
          const values = [
            escapeSQL(category),
            escapeSQL(lawName),
            escapeSQL(articleNum),
            article.isSuppl ? 1 : 0,
            article.isDeleted ? 1 : 0,
            escapeSQL(article.title !== undefined ? article.title : null),
            escapeSQL(article.titleOsaka !== undefined ? article.titleOsaka : null),
            escapeSQL(arrayToJSON(article.originalText)),
            escapeSQL(arrayToJSON(article.osakaText)),
            escapeSQL(arrayToJSON(article.commentary)),
            escapeSQL(arrayToJSON(article.commentaryOsaka)),
          ].join(', ');
          sqlStatements.push(
            `INSERT INTO articles (category, law_name, article, is_suppl, is_deleted, title, title_osaka, original_text, osaka_text, commentary, commentary_osaka) VALUES (${values});`
          );
        }
      }
    }
  }

  // 出力
  console.log(sqlStatements.join('\n'));
}

main();
